/**
 * Acrobatic Command
 * This module aims to generate the desired attitude command in quaternion and convert it to p,q,r(axis rotational rates)
 *
 *
 */
/**< Variables */

#include "AcrobaticPoseControl.h"
#include <px4_log.h>
#include <systemlib/mavlink_log.h>
using namespace time_literals;
using matrix::Quatf;
//#if defined(CONFIG_ARCH_BOARD_PX4_SITL)
//#define TEST_DATA_PATH "./test_data/"
//#else
//#endif

extern "C" __EXPORT int acrobatic_pose_control_main(int argc, char *argv[])
{
    return AcrobaticPoseControl::main(argc, argv);
}

AcrobaticPoseControl::AcrobaticPoseControl():
    WorkItem(MODULE_NAME, px4::wq_configurations::att_pos_ctrl),
    _loop_perf(perf_alloc(PC_ELAPSED, "acrobatic_pose_control: cycle"))
{
    //PX4_INFO("AcrobaticCommand::AcrobaticCommand");
    /**< fetch initial parameter values*/
    /*     parameters    */
    //Related to velocity w
     _parameter_handles.fw_dq_w_i = param_find("FW_DQ_W_I");
     _parameter_handles.fw_dq_w_ff = param_find("FW_DQ_W_FF");
     _parameter_handles.fw_dq_w_p = param_find("FW_DQ_W_P");
    //Related to velocity v
     _parameter_handles.fw_dq_v_i = param_find("FW_DQ_V_I");
     _parameter_handles.fw_dq_v_ff = param_find("FW_DQ_V_FF");
     _parameter_handles.fw_dq_v_p = param_find("FW_DQ_V_P");
    //Related to angular rates p
     _parameter_handles.fw_dq_p_i = param_find("FW_DQ_P_I");
     _parameter_handles.fw_dq_p_ff = param_find("FW_DQ_P_FF");
     _parameter_handles.fw_dq_p_p = param_find("FW_DQ_P_P");


    //Offset in virtual frame
     _parameter_handles.fw_dq_delta_x = param_find("FW_DQ_DELTA_X");
    //Angular rates TC
     _parameter_handles.fw_acro_q0_tc = param_find("FW_DQ_Q0_TC");
     _parameter_handles.fw_acro_q1_tc = param_find("FW_DQ_Q1_TC");
     _parameter_handles.fw_acro_q2_tc = param_find("FW_DQ_Q2_TC");
     _parameter_handles.fw_acro_q3_tc = param_find("FW_DQ_Q3_TC");


    _acrobatic_cmd.acrobatic_finish = false;
    parameters_update();

}

AcrobaticPoseControl::~AcrobaticPoseControl()
{
    //PX4_INFO("AcrobaticCommand::~AcrobaticCommand");
    perf_free(_loop_perf);
}

bool AcrobaticPoseControl::init()
{
    //PX4_INFO("init~~~");
    if(!_att_sub.registerCallback()){
        PX4_ERR("vehicle attitude callback registration failed!");
        return false;
    }
    return true;
}

int
AcrobaticPoseControl::parameters_update()
{
    //PX4_INFO("AcrobaticCommand::parameter_update");
    param_get(_parameter_handles.fw_dq_w_i, &(_parameters.fw_dq_w_i));
    param_get(_parameter_handles.fw_dq_w_ff, &(_parameters.fw_dq_w_ff));
    param_get(_parameter_handles.fw_dq_w_p, &(_parameters.fw_dq_w_p));

    param_get(_parameter_handles.fw_dq_v_i, &(_parameters.fw_dq_v_i));
    param_get(_parameter_handles.fw_dq_v_ff, &(_parameters.fw_dq_v_ff));
    param_get(_parameter_handles.fw_dq_v_p, &(_parameters.fw_dq_v_p));

    param_get(_parameter_handles.fw_dq_p_i, &(_parameters.fw_dq_p_i));
    param_get(_parameter_handles.fw_dq_p_ff, &(_parameters.fw_dq_p_ff));
    param_get(_parameter_handles.fw_dq_p_p, &(_parameters.fw_dq_p_p));

    param_get(_parameter_handles.fw_dq_delta_x, &(_parameters.fw_dq_delta_x));

    param_get(_parameter_handles.fw_acro_q0_tc, &(_parameters.fw_acro_q0_tc));
    param_get(_parameter_handles.fw_acro_q1_tc, &(_parameters.fw_acro_q1_tc));
    param_get(_parameter_handles.fw_acro_q2_tc, &(_parameters.fw_acro_q2_tc));
    param_get(_parameter_handles.fw_acro_q3_tc, &(_parameters.fw_acro_q3_tc));
    return PX4_OK;
}

void
AcrobaticPoseControl::vehicle_cmd_poll()
{
    //In this module, the vehicle_cmd generated in mission block is obtained
    //It is worthy to mention that the vehicle_cmd is the first message to inform
    //the start of acrobatic flight
    _vehicle_cmd_sub.update(&_vehicle_cmd);
}

void
AcrobaticPoseControl::vehicle_global_pos_poll()
{
    //In this module, the global position of the vehicle is obtained
    _global_pos_sub.update(&_global_pos);
}

void
AcrobaticPoseControl::vehicle_local_pos_poll()
{
    //In this module, the local position of the vehicle is obtained
    _local_pos_sub.update(&_local_pos);
}

void
AcrobaticPoseControl::manual_status_poll()
{
    //In this module, the message generated from the manual controller is obtained
    //_man_sub.update(&_man_status);
}
void
AcrobaticPoseControl::vstatus_poll()
{
    //In this module, the status of the vehicle is obtained
    _vstatus_sub.update(&_vstatus);
}

void
AcrobaticPoseControl::acro_setpoint_poll()
{
    //In this module, the setpoint in the form of dual quaternion which is generated by
    //the module acrobatic_commander
    _acro_cmd_sub.update(&_acro_cmd_setpoint);
}

void
AcrobaticPoseControl::Run()
{
        perf_begin(_loop_perf);
        //mavlink_log_info(&_mavlink_log_pub, "TEST_DATA_PATH:%s",TEST_DATA_PATH);
        //PX4_INFO("Running ~~~");
        //mavlink_log_info(&_mavlink_log_pub, "Running");
        if(_att_sub.update(&_att))
        {
            now = hrt_absolute_time();
            _att_q(0) = _att.q[0];
            _att_q(1) = _att.q[1];
            _att_q(2) = _att.q[2];
            _att_q(3) = _att.q[3];

            /**<----------------------    Poll the reference pose    ------------------------------*/
            //Obtain the vehicle command to know whether enters the acrobatic point
            vehicle_cmd_poll();
            //Obtain the global position of the vehicle at this time
            vehicle_global_pos_poll();
            //Obtain the local position of the vehicle at this time
            vehicle_local_pos_poll();
            /*<-----------------------------------------------------------------------------------*/

            /*<-----------------------     Enter acrobatic waypoint     --------------------------*/

            // Enter the acrobatic point
            if(_vehicle_cmd.command == vehicle_command_s::VEHICLE_CMD_DO_ACROBATIC)
            {

                if(_time_first_acrobatic == 0)
                {
                    //initial altitude
                    _alt_first_acrobatic = _global_pos.alt; //The altitude is z*-1 + alt_init
                    _alt_sp_acrobatic = _alt_first_acrobatic;
                    //initial quaternion
                    _quat_first_acro = _att_q;
                    //initial position
                    _xyz_first_acro[0] = _local_pos.x;
                    _xyz_first_acro[1] = _local_pos.y;
                    _xyz_first_acro[2] = _local_pos.z;
                    _time_first_acrobatic = hrt_absolute_time(); //much earlier than the publishing time
                }

                /**<----------------------------  Obtain the dq command -------------------------------------*/
                //whether the setpoint of the acrobatic is generated
                acro_setpoint_poll(); //includes the tag
                DualQuaternion<float> _dq_d;
                Quaternion<float> _quat_d;
                Array<float,3> _xyz_d;
                matrix::Matrix<float, 8, 1> _ref_twist;
                Quaternion<float> _quat_val;
                _quat_val = _att_q;
                if(_acro_cmd_setpoint.setpoint_generated == true)
                {
                    _quat_d = _acro_cmd_setpoint.quat_d;
                    for(size_t i=0; i<3; i++)
                    {
                        _xyz_d[i] = _acro_cmd_setpoint.xyz_d[i];
                    }
                    //_dq_d = Convert_quat_xyz_2_DQ(_xyz_d, _quat_d); edited by caosu
                    _dq_d = Convert_quat_xyz_2_DQ(_xyz_d, _quat_val);
                    for(size_t i=0;i<8;i++)
                    {
                        _ref_twist(i,0) = _acro_cmd_setpoint.ref_twist[i];
                    }

                }
                else
                {
                    //The setpoint has not been calculated yet, set the desired pose as the initial status
                    _quat_d = _quat_first_acro;
                    _xyz_d[0] = _local_pos.x;
                    _xyz_d[1] = _local_pos.y;
                    _xyz_d[2] = _xyz_first_acro[2];
                }
                /**<----------------------- Obtain the twist command ----------------------------------------*/
                //Obtain current pose

                Array<float, 3> _xyz_val;
                _xyz_val[0] = _local_pos.x - _xyz_first_acro[0];
                _xyz_val[1] = _local_pos.y - _xyz_first_acro[1];
                _xyz_val[2] = _local_pos.z - _xyz_first_acro[2];
                DualQuaternion<float> _dq_val;
                _dq_val = Convert_quat_xyz_2_DQ(_xyz_val, _quat_val);
                //_dq_val = Convert_quat_xyz_2_DQ(_xyz_val, _quat_d); //replace the quad_val with quad_d

                matrix::Matrix<float, 8, 1> _com_twist;
                //_ref_twist = interp_1_d_pqr_uvw();
                _com_twist = Twist_Command_Gen(_dq_d, _dq_val, _ref_twist);

                matrix::Matrix<float, 3, 1> _angular_body_setpoint;
                _angular_body_setpoint = Angular_rates_control(_quat_d, _quat_val);

                /**<--------------------------- Publish the debug -------------------------------------------*/
                acrobatic_debug_s _acro_debug;
                _acro_debug.timestamp = hrt_absolute_time();
                _acro_debug.timestamp_init = _time_first_acrobatic;
                _acro_debug.do_acrobatic = true;
                _acro_debug.xyz_setpoint[0] = _xyz_d[0];
                _acro_debug.xyz_setpoint[1] = _xyz_d[1];
                _acro_debug.xyz_setpoint[2] = _xyz_d[2];
                _acro_debug.xyz_val[0] = _xyz_val[0];
                _acro_debug.xyz_val[1] = _xyz_val[1];
                _acro_debug.xyz_val[2] = _xyz_val[2];
                _acro_debug.quaternion_setpoint[0] = _quat_d(0);
                _acro_debug.quaternion_setpoint[1] = _quat_d(1);
                _acro_debug.quaternion_setpoint[2] = _quat_d(2);
                _acro_debug.quaternion_setpoint[3] = _quat_d(3);
                _acro_debug.quaternion_val[0] = _quat_val(0);
                _acro_debug.quaternion_val[1] = _quat_val(1);
                _acro_debug.quaternion_val[2] = _quat_val(2);
                _acro_debug.quaternion_val[3] = _quat_val(3);

                _acro_debug.dq_d_real[0] = _dq_d.m_real(0);
                _acro_debug.dq_d_real[1] = _dq_d.m_real(1);
                _acro_debug.dq_d_real[2] = _dq_d.m_real(2);
                _acro_debug.dq_d_real[3] = _dq_d.m_real(3);
                _acro_debug.dq_d_dual[0] = _dq_d.m_dual(0);
                _acro_debug.dq_d_dual[1] = _dq_d.m_dual(1);
                _acro_debug.dq_d_dual[2] = _dq_d.m_dual(2);
                _acro_debug.dq_d_dual[3] = _dq_d.m_dual(3);

                _acro_debug.dq_v_real[0] = _dq_val.m_real(0);
                _acro_debug.dq_v_real[1] = _dq_val.m_real(1);
                _acro_debug.dq_v_real[2] = _dq_val.m_real(2);
                _acro_debug.dq_v_real[3] = _dq_val.m_real(3);
                _acro_debug.dq_v_dual[0] = _dq_val.m_dual(0);
                _acro_debug.dq_v_dual[1] = _dq_val.m_dual(1);
                _acro_debug.dq_v_dual[2] = _dq_val.m_dual(2);
                _acro_debug.dq_v_dual[3] = _dq_val.m_dual(3);

                _acro_debug_pub.publish(_acro_debug);

                //mavlink_log_info(&_mavlink_log_pub, "Twist Command(PQR): %.2lf\t%.2lf\t%.2lf\t%.2lf",
                //                (double)_com_twist(0,0),(double)_com_twist(1,0),
                //                (double)_com_twist(2,0),(double)_com_twist(3,0));
                //mavlink_log_info(&_mavlink_log_pub, "Twist Command(UVW): %.2lf\t%.2lf\t%.2lf",
                //                (double)_com_twist(5,0),(double)_com_twist(6,0),(double)_com_twist(7,0));
                //float w = _local_pos.vz;
                //_alt_sp_acrobatic += -1 * (float)((now-time_prev)/1e6) * w; //transfer according to the frame









                // Calculate the true
                // flight velocity v_sp and w_sp
                matrix::Vector3f ground_speed(_global_pos.vel_n, _global_pos.vel_e,  _global_pos.vel_d);
                //calculate the velocity in body frame
                // Velocity in body frame
                const matrix::Dcmf R_to_body(Quatf(_att.q).inversed());
                const matrix::Vector3f vel = R_to_body * matrix::Vector3f(ground_speed(0), ground_speed(1), ground_speed(2));

                //const float _vel_x_real = vel(0);
                _v_real = vel(1);
                _w_real = vel(2);
                _u_real = vel(0);

                /*------------------- Added 20220708 ------------------------*/
                //Transfer the u,v,w real to virtual frame
                //Calculate the real frame twist
                DualQuaternion<float> _twist_real;
                DualQuaternion<float> _twist_virtual;
                vehicle_angular_velocity_s angular_velocity;
                _vehicle_rates_sub.copy(&angular_velocity);
                float _p_real = angular_velocity.xyz[0];
                float _q_real = angular_velocity.xyz[1];
                float _r_real = angular_velocity.xyz[2];
                _twist_real.m_real(1) = _p_real;
                _twist_real.m_real(2) = _q_real;
                _twist_real.m_real(3) = _r_real;
                _twist_real.m_dual(1) = _u_real;
                _twist_real.m_dual(2) = _v_real;
                _twist_real.m_dual(3) = _w_real;
                DualQuaternion<float> _hat_q_delta;
                float _delta = 1;
                _hat_q_delta.m_real(0) = 1;
                _hat_q_delta.m_dual(1) = -1*_delta;
                _twist_virtual = _hat_q_delta.conjugate()*_twist_real;
                _twist_virtual = _twist_virtual*_hat_q_delta;
                //Transfer the reference twist to virtual frame
                DualQuaternion<float> _twist_ref;
                DualQuaternion<float> _twist_ref_virtual;
                _twist_ref.m_real(0) = _com_twist(0,0);
                _twist_ref.m_real(1) = _com_twist(1,0);
                _twist_ref.m_real(2) = _com_twist(2,0);
                _twist_ref.m_real(3) = _com_twist(3,0);
                _twist_ref.m_dual(0) = _com_twist(4,0);
                _twist_ref.m_dual(1) = _com_twist(5,0);
                _twist_ref.m_dual(2) = _com_twist(6,0);
                _twist_ref.m_dual(3) = _com_twist(7,0);
                _twist_ref_virtual = _hat_q_delta.conjugate()*_twist_ref;
                _twist_ref_virtual = _twist_ref_virtual*_hat_q_delta;

                /*----------------------------Send Command TECS-----------------------------------------*/
                _alt_sp_acrobatic = _alt_first_acrobatic - _xyz_d[2];
                _acrobatic_cmd.timestamp = hrt_absolute_time();
                _acrobatic_cmd.xyz_first_acro[0] = _xyz_first_acro[0];
                _acrobatic_cmd.xyz_first_acro[1] = _xyz_first_acro[1];
                _acrobatic_cmd.xyz_first_acro[2] = _xyz_first_acro[2];
                _acrobatic_cmd.do_acrobatic = true;
                _acrobatic_cmd.alt_sp_acrobatic = _alt_sp_acrobatic;//_xyz_d[2];

                _acrobatic_cmd.airsp_sp = _twist_ref_virtual.m_dual(1); //20220708
                _acrobatic_cmd.v_sp = _twist_ref_virtual.m_dual(2); //20220708
                _acrobatic_cmd.w_sp = _twist_ref_virtual.m_dual(3); //20220708


                //_acrobatic_cmd.airsp_sp = 60;//_com_twist(5,0); 20220708
                //_acrobatic_cmd.v_sp = _com_twist(6,0); //edited by caosu 20220708
                //_acrobatic_cmd.w_sp = 1.5 + sin(float(now/(1*1e6)));//_com_twist(7,0); edited by caosu
                //_acrobatic_cmd.w_sp = _com_twist(7,0); 20220708
                //_acrobatic_cmd.euler_cmd[0] = asinf(2*(_dq_d.m_real(0)*_dq_d.m_real(2)-_dq_d.m_real(3)*_dq_d.m_real(1)));
                _acrobatic_cmd.euler_cmd[0] = asinf(2*(_att_q(0)*_att_q(2)-_att_q(3)*_att_q(1)));

                _acrobatic_cmd.body_rates_cmd[0] = _angular_body_setpoint(0,0);//_com_twist(1,0);
                _acrobatic_cmd.body_rates_cmd[1] = 0;//_com_twist(2,0);
                _acrobatic_cmd.body_rates_cmd[2] = 0;//_com_twist(3,0);
                /*--------------------------------------------------------------------------------------*/

                // Preparing the publishment

                //_acrobatic_cmd.v_real = _v_real; 20220708
                //_acrobatic_cmd.w_real = _w_real; 20220708
                _acrobatic_cmd.v_real = _twist_virtual.m_dual(2); //20220708
                _acrobatic_cmd.w_real = _twist_virtual.m_dual(3); //20220708
                _acrobatic_cmd.u_real = _twist_virtual.m_dual(1); //20220708
                _acrobatic_cmd.u_sp_cal = _u_cal_tmp;
                _acrobatic_cmd.v_sp_cal = _v_cal_tmp;
                _acrobatic_cmd.w_sp_cal = _w_cal_tmp;
                //_acrobatic_cmd.u_real = _u_real; 20220708
                _acrobatic_cmd.vel_total = sqrt(_u_real*_u_real + _v_real*_v_real + _w_real*_w_real);
                _acrobatic_cmd.quaternion_cmd[0] = _dq_d.m_real(0);
                _acrobatic_cmd.quaternion_cmd[1] = _dq_d.m_real(1);
                _acrobatic_cmd.quaternion_cmd[2] = _dq_d.m_real(2);
                _acrobatic_cmd.quaternion_cmd[3] = _dq_d.m_real(3);
                _acrobatic_cmd.acrobatic_finish = _acro_cmd_setpoint.acrobatic_finish;
                _acro_cmd_pub.publish(_acrobatic_cmd);
                mavlink_log_info(&_mavlink_log_pub, "Publishing the acrobatic command ~~~");

            }
            /*Storage the demonstration*/
            //Twist_Demon_Storage();
            time_prev = now;
        }
        perf_end(_loop_perf);
    //}
}


void AcrobaticPoseControl::Twist_Demon_Storage()
{
    /*This function is to storage the twist during demonstration*/
    // Calculate the true
    // flight velocity v_sp and w_sp
    matrix::Vector3f ground_speed(_global_pos.vel_n, _global_pos.vel_e,  _global_pos.vel_d);
    //calculate the velocity in body frame
    // Velocity in body frame
    const matrix::Dcmf R_to_body(Quatf(_att.q).inversed());
    const matrix::Vector3f vel = R_to_body * matrix::Vector3f(ground_speed(0), ground_speed(1), ground_speed(2));

    // the linear velocities in the body frame
    float _u_real_storage = vel(0);
    float _v_real_storage = vel(1);
    float _w_real_storage = vel(2);

    // the angular velocities in the body frame
    //vehicle_angular_velocity_s angular_velocity{};
    vehicle_angular_velocity_s angular_velocity;
    _vehicle_rates_sub.copy(&angular_velocity);
    float rollspeed_storage = angular_velocity.xyz[0];
    float pitchspeed_storage = angular_velocity.xyz[1];
    float yawspeed_storage = angular_velocity.xyz[2];

    acrobatic_demo_s _acro_demo;
    _acro_demo.timestamp = hrt_absolute_time();
    _acro_demo.angular_velocity[0] = rollspeed_storage;
    _acro_demo.angular_velocity[1] = pitchspeed_storage;
    _acro_demo.angular_velocity[2] = yawspeed_storage;
    _acro_demo.linear_velocity[0] = _u_real_storage;
    _acro_demo.linear_velocity[1] = _v_real_storage;
    _acro_demo.linear_velocity[2] = _w_real_storage;
    _acro_demo_pub.publish(_acro_demo);
}


matrix::Matrix<float, 8, 1> AcrobaticPoseControl::Twist_Command_Gen(const DualQuaternion<float> _dual_quat_cmd,
                                                           const DualQuaternion<float> _dual_quat_val,
                                                           const matrix::Matrix<float, 8, 1> _ref_twist){ //verified
     DualQuaternion<float> _hat_q_e;
     _hat_q_e = _dual_quat_cmd.conjugate() * _dual_quat_val;
     DualQuaternion<float> _pose_err;
     _pose_err = _hat_q_e.DQError_truepos();
     matrix::Matrix<float, 8, 8> _Hat_G_e;
     _Hat_G_e = Hat_G_mat(_hat_q_e);
     matrix::Matrix<float, 8, 8> _inv_Hat_G_e;
     _inv_Hat_G_e = inv_Hat_G_mat_cal(_Hat_G_e);
     matrix::Matrix<float, 8, 1> _pose_err_val;
     for(size_t i=0; i<4; i++){
        _pose_err_val(i,0) = _pose_err.m_real(i);
        _pose_err_val(i+4,0) = _pose_err.m_dual(i);
     }
     matrix::Matrix<float, 8, 1> _omega_e;
     matrix::Matrix<float, 8, 8> _mat_gain;
     for(size_t i=0; i<8; i++)
     {
         _pos_err_val_tmp[i] = _pose_err_val(i,0);
     }
     _mat_gain(1,1) = -0.1;
     _mat_gain(2,2) = -0.1;
     _mat_gain(3,3) = -0.1;
     _mat_gain(5,5) = -0.1;
     _mat_gain(6,6) = -0.1;
     _mat_gain(7,7) = -0.1;
     for(size_t i=0; i<8; i++)
     {
         _pose_err_val(i,0) *= _mat_gain(i,i);
         _pose_err_val(i,0) *= -1;
     }
     for(size_t i=0; i<8; i++)
     {
         for(size_t j=0; j<8; j++)
         {
             _Hat_G_inv_tmp[i*8+j] = _inv_Hat_G_e(i,j);
         }
     }
     //_omega_e = float(1) * _inv_Hat_G_e * (_mat_gain*_pose_err_val);
     _omega_e = _inv_Hat_G_e * _pose_err_val;

     matrix::Matrix<float, 8, 1> _com_twist;
     //_com_twist = _ref_twist;//_omega_e + _ref_twist; //eddited by caosu
     _com_twist = _ref_twist;
     //_com_twist = _omega_e + _ref_twist;

     _u_cal_tmp = _omega_e(5,0); //obtain the u value
     _v_cal_tmp = _omega_e(6,0); //obtain the v value
     _w_cal_tmp = _omega_e(7,0); //obtain the w value
     return _com_twist;
}

matrix::Matrix<float, 3, 1> AcrobaticPoseControl::Angular_rates_control(Quaternion<float> _quat_d,
                                                                        Quaternion<float> _att_q_val){
    Quaternion<float> _quat_e;
    float _fw_acro_q0_tc, _fw_acro_q1_tc, _fw_acro_q2_tc, _fw_acro_q3_tc;
    _fw_acro_q0_tc = 0.5;
    _fw_acro_q1_tc = 0.5;
    _fw_acro_q2_tc = 0.5;
    _fw_acro_q3_tc = 0.5;
    _quat_e(0) = (_quat_d(0) - _att_q_val(0))/_fw_acro_q0_tc;
    _quat_e(1) = (_quat_d(1) - _att_q_val(1))/_fw_acro_q1_tc;
    _quat_e(2) = (_quat_d(2) - _att_q_val(2))/_fw_acro_q2_tc;
    _quat_e(3) = (_quat_d(3) - _att_q_val(3))/_fw_acro_q3_tc;
    matrix::Matrix<float, 3, 1> _angular_body_setpoint;
    _angular_body_setpoint(0,0) = 2 * _att_q_val(0) * _quat_e(1) - 2 * _att_q_val(1) * _quat_e(0)
            - 2 * _att_q_val(2) * _quat_e(3) + 2 * _att_q_val(3) * _quat_e(2);
    _angular_body_setpoint(1,0) = 2 * _att_q(0) * _quat_e(2) - 2 * _att_q(2) * _quat_e(0)
            + 2 * _att_q_val(1) * _quat_e(3) - 2 * _att_q_val(3) * _quat_e(1);
    _angular_body_setpoint(2,0) = 2 * _att_q(0) * _quat_e(3) - 2 * _att_q(1) * _quat_e(2)
            + 2 * _att_q_val(2) * _quat_e(1) - 2 * _att_q_val(3) * _quat_e(0);
    return _angular_body_setpoint;
}




DualQuaternion<float> AcrobaticPoseControl::Convert_quat_xyz_2_DQ(const Array<float,3> _xyz, const Quaternion<float> _att_d){
    DualQuaternion<float> _hat_q_n_d;
    _hat_q_n_d.m_real = _att_d;
    Quaternion<float> _xyz_d;
    for(size_t i=0;i<3;i++){
        _xyz_d(i+1) = _xyz[i];
    }
    _xyz_d = _xyz_d * _att_d;
    _hat_q_n_d.m_dual = float(0.5) * _xyz_d;
    return _hat_q_n_d;
}



matrix::Matrix<float, 8, 8> AcrobaticPoseControl::Hat_G_mat(DualQuaternion<float> hat_q_e) const{ //verified
    matrix::Matrix<float, 8, 8> Hat_G_mat;
    matrix::Matrix<float, 4, 4> T_mat_q_mp, S_mat_q_mp;
    Quaternion<float> hat_q_e_1, hat_q_e_2;
    hat_q_e_1(0) = hat_q_e.m_real(0);
    hat_q_e_2 = hat_q_e.m_real;
    hat_q_e_2(0) = 0;
    T_mat_q_mp = hat_q_e.T_mat_q(hat_q_e_1);
    S_mat_q_mp = hat_q_e.S_mat_q(hat_q_e_2);
    for(size_t i=0; i<4; i++){
        for(size_t j=0; j<4; j++){
            if(hat_q_e.m_real(0)>0)
            {
                Hat_G_mat(i,j) = 2*T_mat_q_mp(i,j) + S_mat_q_mp(i,j);
            }
            else
            {
                Hat_G_mat(i,j) = -2*T_mat_q_mp(i,j) - S_mat_q_mp(i,j);
            }
        }
    }
    Quaternion<float> p_e_c;
    p_e_c = hat_q_e.quatConjugate(hat_q_e.m_real)*hat_q_e.m_dual;
    p_e_c *= 2;
    matrix::Matrix<float, 4, 4> S_mat_q_mp2;
    S_mat_q_mp2 = hat_q_e.S_mat_q(p_e_c);
    S_mat_q_mp2 *= -1;
    for(size_t i=0; i<4; i++){
        for(size_t j=0; j<4; j++){
            Hat_G_mat(i+4,j) = S_mat_q_mp2(i,j);
        }
    }
    Quaternion<float> quat_I;
    quat_I(0) = 1;
    matrix::Matrix<float, 4, 4> T_mat_q_mp2;
    T_mat_q_mp2 = hat_q_e.T_mat_q(quat_I);
    T_mat_q_mp2 *= 2;
    for(size_t i=0; i<4; i++){
        for(size_t j=0; j<4; j++){
            Hat_G_mat(i+4,j+4) = T_mat_q_mp2(i,j);
        }
    }

    Hat_G_mat = float(0.25)*Hat_G_mat;
    return Hat_G_mat;


}

matrix::Matrix<float, 3, 3> AcrobaticPoseControl::inv_three_order(const matrix::Matrix<float, 3, 3> mat_A) const{ // verified
    float a1, a2, a3, b1, b2, b3, c1, c2, c3;
    a1 = mat_A(0,0);
    a2 = mat_A(1,0);
    a3 = mat_A(2,0);
    b1 = mat_A(0,1);
    b2 = mat_A(1,1);
    b3 = mat_A(2,1);
    c1 = mat_A(0,2);
    c2 = mat_A(1,2);
    c3 = mat_A(2,2);

    float det_mat_A = float(float(1.0)/(float(1.0)*(a1*(b2*c3-c2*b3) - a2*(b1*c3-c1*b3) + a3*(b1*c2-c1*b2))));
    matrix::Matrix<float, 3, 3> inv_mat_A;
    inv_mat_A(0,0) = b2*c3 - c2*b3;
    inv_mat_A(0,1) = c1*b3 - b1*c3;
    inv_mat_A(0,2) = b1*c2 - c1*b2;
    inv_mat_A(1,0) = c2*a3 - a2*c3;
    inv_mat_A(1,1) = a1*c3 - c1*a3;
    inv_mat_A(1,2) = a2*c1 - a1*c2;
    inv_mat_A(2,0) = a2*b3 - b2*a3;
    inv_mat_A(2,1) = b1*a3 - a1*b3;
    inv_mat_A(2,2) = a1*b2 - a2*b1;

    if(fabs(det_mat_A) > 1e-5){
        inv_mat_A = inv_mat_A * det_mat_A;
    }

    return inv_mat_A;
}

matrix::Matrix<float, 8, 8> AcrobaticPoseControl::inv_Hat_G_mat_cal(const matrix::Matrix<float, 8, 8> Hat_G_mat) const{ // verified
    matrix::Matrix<float, 4, 4> inv_Hat_G_mat_1, inv_Hat_G_mat_2, inv_Hat_G_mat_3;
    matrix::Matrix<float, 3, 3> mat_temp, inv_mat_temp;
    inv_Hat_G_mat_1(0,0) = float(1.0) / Hat_G_mat(0,0);
    for(size_t i=0; i<3; i++)
        for(size_t j=0; j<3; j++)
        {
            mat_temp(i,j) = Hat_G_mat(i+1,j+1);
        }
    inv_mat_temp = inv_three_order(mat_temp);
    for(size_t i=0; i<3; i++)
        for(size_t j=0; j<3; j++)
        {
            inv_Hat_G_mat_1(i+1,j+1) = inv_mat_temp(i,j);
        }

    float inv_num_temp;
    inv_num_temp = float(1.0)/Hat_G_mat(6,6);
    inv_Hat_G_mat_3(0,0) = inv_num_temp;
    inv_Hat_G_mat_3(1,1) = inv_num_temp;
    inv_Hat_G_mat_3(2,2) = inv_num_temp;
    inv_Hat_G_mat_3(3,3) = inv_num_temp;

    for(size_t i=0; i<4; i++){
        for(size_t j=0; j<4; j++){
            inv_Hat_G_mat_2(i,j) = Hat_G_mat(i+4,j);
        }
    }
    inv_Hat_G_mat_2 = -float(1.0)*inv_Hat_G_mat_3*inv_Hat_G_mat_2;
    inv_Hat_G_mat_2 = inv_Hat_G_mat_2 * inv_Hat_G_mat_1;
    matrix::Matrix<float, 8, 8> inv_Hat_G_mat;
    for(size_t i=0; i<4; i++){
        for(size_t j=0; j<4; j++){
            inv_Hat_G_mat(i,j) = inv_Hat_G_mat_1(i,j);
            inv_Hat_G_mat(i+4,j) = inv_Hat_G_mat_2(i,j);
            inv_Hat_G_mat(i+4,j+4) = inv_Hat_G_mat_3(i,j);
        }
    }
    return inv_Hat_G_mat;
}



//matrix::Matrix<T, 8, 8> AcrobaticDQ::Hat_G_mat(DualQuaternion<T> dq1) const{}


int AcrobaticPoseControl::task_spawn(int argc, char *argv[])  /**< generate a task */
{

    AcrobaticPoseControl *instance = new AcrobaticPoseControl();

    if(instance){
        _object.store(instance);
        _task_id = task_id_is_work_queue;

        if(instance->init())
        {
            return PX4_OK;
        }
    } else {
        PX4_ERR("alloc failed");
    }

    delete instance;
    _object.store(nullptr);
    _task_id = -1;

    return PX4_ERROR;

    return 0;

}

int AcrobaticPoseControl::custom_command(int argc, char *argv[])
{
    //PX4_INFO("custom_command~~");
    return print_usage("unknown command");
}


int AcrobaticPoseControl::print_status()
{
    //PX4_INFO("print_status");
    perf_print_counter(_loop_perf);
    return 0;
}

int AcrobaticPoseControl::print_usage(const char *reason)
{
    if(reason){
        PX4_WARN("%s\n", reason);
    }
    //PX4_INFO("print_usage");

    PRINT_MODULE_DESCRIPTION(
                R"DESCR_STR(
                ### Description
                acrobatic_pose_control is the fixed wing acrobatic command generator.

                )DESCR_STR"
                );
    PRINT_MODULE_USAGE_COMMAND("start");
    PRINT_MODULE_USAGE_NAME("acrobatic_pose_control", "controller");
    PRINT_MODULE_USAGE_DEFAULT_COMMANDS();

    return 0;
}
